project:
  type: website
  output-dir: docs
website:
  title: "DataSci"
  announcement: 
    content: "Website Under Construction!"
  description: "LING 0700 | PSYC 2314"
  sidebar:
    style: "docked"
    logo: "logo.png"
    # background: "#f3f1ed"
    search: true
    # tools: 
    #   - icon: rocket
    #     href: https://colab.research.google.com
    #     text: "Google Colab"
    #   - icon: lifesaver
    #     href: https://edstem.org/us/courses/XXXX/discussion/
    #     text: "Ed Discussion"
    contents:
    - text: "Syllabus"
      href: index.qmd
    - text: "Assignments"
      href: index.qmd#assignments
    - text: "Schedule"
      href: index.qmd#schedule
    # - text: "Syllabus"
    #   href: syllabus.qmd
    # - text: "Materials"
    #   href: materials.qmd
    # - text: "Textbook"
    # - text: "Resources"
    #   href: resources.qmd
    # - text: "FAQs"
    #   href: faqs.qmd
    # - text: "AI Policy"
    #   href: ai-policy.qmd
  # navbar:
  #   left:
  #     # - href: index.qmd
  #     #   text: Home
  #     - syllabus.qmd
  #     - schedule.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



