project:
  type: website
  output-dir: docs
website:
  title: DataSci
  announcement:
    content: First lab on Thurs/Fri!
  description: LING 0700 | PSYC 2314
  sidebar:
    style: docked
    logo: logo.png
    search: true
    contents:
    - text: Syllabus
      href: index.qmd
    - text: Canvas
      icon: bi-box-arrow-up-right
      href: https://canvas.upenn.edu/courses/1879865
    - text: Ed Discussion
      icon: bi-chat-square-dots
      href: https://edstem.org/us/courses/85059
format:
  html:
    theme: cosmo
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
