---
title: "Data science for studying language & the mind"
subtitle: "Fall 2025"
format: 
    html: default
    pdf: default
---

## Syllabus

**Course description**: Data Sci for Lang & Mind is an entry-level course designed to teach basic principles of statistics and data science to students with little or no background in statistics or computer science. Students will learn to identify patterns in data using visualizations and descriptive statistics; make predictions from data using machine learning and optimization; and quantify the certainty of their predictions using statistical models. This course aims to help students build a foundation of critical thinking and computational skills that will allow them to work with data in all fields related to the study of the mind (e.g. linguistics, psychology, philosophy, cognitive science, neuroscience).

**Prerequisites**: There are *no prerequisites beyond high school algebra*. No prior programming or statistics experience is necessary, though you will still enjoy this course if you already have a little. Students who have taken several computer science or statistics classes should look for a more advanced course.

**Professor**: [Dr. Katie Schuler](https://kathrynschuler.com) (likes to be called Katie). I really enjoy getting to know students outside of class. Here are a few ways to connect with me: 

- **Office Hours**: Day/Time TBD, 3401-C Walnut, 314C. Drop in for questions/ideas or just to chat.
- **Snack & Share**: Join me weekdays at 1:30pm in the Linguistics Library (15 min free snack break)

**TAs**:

- [Brittany Zykoski](https://www.ling.upenn.edu/people/brittany-zykoski)
- [Mingyang Bian](https://www.ling.upenn.edu/people/mingyang-bian)
- [Izabela Baran](mailto:ibaran@sas.upenn.edu)

**Lectures**: Tuesdays and Thursdays from 12 - 1:29pm in COHN 402.

**Labs**: Hands-on practice and exam prep guided by TAs.

* 402: Fri at 3:30-4:29p in WILL 316 with Brittany 
* 403: Thu at 1:45-2:44p in WILL 204 with Brittany 
* 405: Fri at 12:00-12:59p in WILL 321 with Mingyang (and Izabela)
* 406: Thu at 5:15-6:14p in BENN 322 with Mingyang (and Izabela)

**Office Hours**: You are welcome to attend any office hours that fit your schedule. The linguistics department is located on the 3rd floor of 3401-C Walnut street, between Franklin's Table and Modern Eye. 

- Katie Schuler: TBD in 314C
- Brittany Zykoski: TBD 
- Mingyang Bian: Thursdays 10:30-11:30 in 325C. 

**Grading**:

- 20% Homework (equally weighted, lowest dropped)
- 20% Lab Attendance/Participation (up to 2 absences excused without penalty)
- 60% Exams (equally weighted, final is optional to replace lowest exam)

**Collaboration**: Collaboration on problem sets and labs is highly encouraged! If you collaborate on psets, you need to write your own code/solutions, name your collaborators, and cite any outside sources you consulted (you don't need to cite the course material).

**Accomodations**: We will fully support any accommodations arranged through Disability Services via the [Weingarten Center](https://weingartencenter.universitylife.upenn.edu/disability-services/). If class conflicts with a religious holiday you observe, we are happy to make alternate arrangements. Please let us know early in either case so we can plan ahead.

**Extra credit**: There is no extra credit in the course. However, students can submit any missed problem set or exam by the end of the semester for half credit (50%) to boost their grade.

**Regrade requests** Regrade requests should be submitted through Gradescope within one week of receiving your graded assignment. Please explain why you believe there was a grading mistake, given the posted solutions and rubric


## Assignments 

Assignments for the Fall 2025 semester will be posted below. Last years materials are avilable [here](https://kschuler.github.io/datasci/#materials)

### Problem sets

There are 9 problem sets, due to Gradescope by noon on the following Mondays. You may request an extension of up to 3 days for any reason. After solutions are posted, late problem sets can still be submitted for half credit (50%). Your lowest score will be dropped. 

- [Pset 1 (Monday Sep 8)](psets/pset-01.qmd)
- Pset 2 (Monday Sep 15)
- Pset 3 (Monday Sep 22)
- Pset 4 (Monday Sep 29)
- Pset 5 (Monday Oct 20)
- Pset 6 (Monday Oct 27)
- Pset 7 (Monday Nov 3)
- Pset 8 (Monday Nov 17)

### Exams 
There are 2 midterm exams, taken in class on the following dates. Exams cannot be rescheduled, except in cases of genuine conflict or emergency (documentation and a Course Action Notice are required). However, you can submit any missed exam by the end of the semester for half credit (50%). You may also replace your lowest midterm exam score with the optional final exam.

- Midterm 1 (Thursday, October 2)
- Midterm 2 (Thursday November 20)
- Optional Final Exam (TBD)

### Lab exercises 

Lab exercises are designed for practice and skill-building. They are not collected or graded. However, lab attendance is required and will count toward your course grade. You may miss up to 2 labs (for reasons such as illness or travel) without penalty.Notify your section TA if you must miss a lab. 

- [Lab 1 R Basics & Data Visualization](labs/lab-01.qmd)
- Lab 2 Data wrangling
- Lab 3 Sampling
- Lab 4 Hypothesis testing
- Lab 5 Model specification
- Lab 6 Model fitting
- Lab 7 Model evaluation 
- Lab 8 Feature engineering (topic may change)
- Lab 9 (optional)

## Schedule

All coding demos can be found [here](https://drive.google.com/drive/folders/1l9j6yEcL7rk6c6IUhKZOnRtO8lnsJx3O?usp=sharing). Homeworks are now shown the week they are *released* (due the following Monday). 

| Week | Begins |  Topic | Materials | Lab (Thu/Fri) | Homework  |
| -  | -- |  --- | ---- | --- | --- |
| 1 | Aug 26 | R Basics  | [slides](slides/r-basics.qmd), [demo](https://colab.research.google.com/drive/1Tv0Obx3hGCX9Zi956jI7_5SuRO5T95h8?usp=drive_link) | No lab! | |
| 2 | Sep 4 | Data visualization | [slides](slides/data-visualization.qmd), [demo](https://colab.research.google.com/drive/1eCKrIvYBn9-EoKAsh1_FWcRCVl5nLO7G?usp=sharing) | [Lab 1](labs/lab-01.qmd) | [Pset 1](psets/pset-01.qmd) |
| 3 | Sep 9 | Data wrangling | |  Lab 2 | Pset 2 |
| 4 | Sep 16 | Sampling distribution | |  Lab 3 | Pset 3 | 
| 5 | Sep 23 | Hypothesis testing<br> | | Lab 4 | Pset 4 |
| 6 | Sep 30 | Midterm 1 review (Tue)<br>Midterm 1 (Thu) |  | |  |
| 7 | Oct 7 | Make-up date Midterm 1<br>**Fall break, no class/lab**| | | 
| 8 | Oct 14 | Model specification | | Lab 5 | Pset 5 | 
| 9 | Oct 21 | Model fitting | | Lab 6 | Pset 6  | 
| 10 | Oct 28 | Model evaluation | | Lab 7 | Pset 7 |
| 11 | Nov 4 | **Katie conference, no class/lab** | | |  |
| 12 | Nov 11 | Feature engineering (??) | |  Lab 8 | Pset 8 | 
| 13 | Nov 18 | Miterm 2 review (Tue)<br>Midterm 2 (Thu) | | |   | 
| 14 | Nov 25 |**Thanksgiving break, no class/lab**  |    |
| 15 | Dec 2 | Careers in datasci lunch! | |  Lab 9 |  |
| 16 | Dec 9 | **Last week of class, no class/lab** |  |  |  |
| 17 | TBD | Final exam (optional) |

